modelFile: models/mochilero24.mzn
dzn_dataFile: output/dzn_data/data.dzn
domainFile: domains/dominioMochilero24.pddl
problemFile: output/problems/problem.pddl
domainName: dominioMochilero
pddlCorrespondence:
  closedoor:
  - (haySalida)
  - (enSuelo Recurso8)
  - (= (peso Recurso8) 1)
  - (= (posicion Recurso8) 8)
  - (enSuelo Recurso9)
  - (= (peso Recurso9) 4)
  - (= (posicion Recurso9) 9)
  - (enSuelo Recurso10)
  - (= (peso Recurso10) 5)
  - (= (posicion Recurso10) 10)
  - (enSuelo Recurso11)
  - (= (peso Recurso11) 2)
  - (= (posicion Recurso11) 11)
  - (enSuelo Recurso12)
  - (= (peso Recurso12) 3)
  - (= (posicion Recurso12) 12)
  - (requiere Recurso8 Recurso7)
  - (requiere Recurso9 Recurso8)
  - (requiere Recurso10 Recurso9)
  - (requiere Recurso11 Recurso10)
  - (requiere Recurso12 Recurso11)
  - (enSuelo Recurso13)
  - (requiere Recurso13 Recurso12)
  - (= (peso Recurso13) 3)
  - (= (posicion Recurso13) 13)
  - (enSuelo Recurso14)
  - (requiere Recurso14 Recurso13)
  - (= (peso Recurso14) 1)
  - (= (posicion Recurso14) 14)
  - (enSuelo Recurso15)
  - (requiere Recurso15 Recurso14)
  - (= (peso Recurso15) 7)
  - (= (posicion Recurso15) 15)
  - (enSuelo Recurso16)
  - (requiere Recurso16 Recurso15)
  - (= (peso Recurso16) 2)
  - (= (posicion Recurso16) 16)
  - (enSuelo Recurso17)
  - (requiere Recurso17 Recurso16)
  - (= (peso Recurso17) 6)
  - (= (posicion Recurso17) 17)
  - (enSuelo Recurso18)
  - (requiere Recurso18 Recurso17)
  - (= (peso Recurso18) 3)
  - (= (posicion Recurso18) 18)
  - (enSuelo Recurso19)
  - (requiere Recurso19 Recurso18)
  - (= (peso Recurso19) 4)
  - (= (posicion Recurso19) 19)
  - (enSuelo Recurso20)
  - (requiere Recurso20 Recurso19)
  - (= (peso Recurso20) 9)
  - (= (posicion Recurso20) 20)
  - (enSuelo Recurso21)
  - (requiere Recurso21 Recurso20)
  - (= (peso Recurso21) 1)
  - (= (posicion Recurso21) 21)
  - (enSuelo Recurso22)
  - (requiere Recurso22 Recurso21)
  - (= (peso Recurso22) 7)
  - (= (posicion Recurso22) 22)
  - (enSuelo Recurso23)
  - (requiere Recurso23 Recurso22)
  - (= (peso Recurso23) 2)
  - (= (posicion Recurso23) 23)
  - (enSuelo Recurso24)
  - (requiere Recurso24 Recurso23)
  - (= (peso Recurso24) 6)
  - (= (posicion Recurso24) 24)
  recurso1:
  - (enSuelo Recurso1)
  - (= (peso Recurso1) 1)
  - (= (posicion Recurso1) 1)
  recurso2:
  - (enSuelo Recurso2)
  - (requiere Recurso2 Recurso1)
  - (= (peso Recurso2) 2)
  - (= (posicion Recurso2) 2)
  recurso3:
  - (enSuelo Recurso3)
  - (requiere Recurso3 Recurso2)
  - (= (peso Recurso3) 3)
  - (= (posicion Recurso3) 3)
  recurso4:
  - (enSuelo Recurso4)
  - (requiere Recurso4 Recurso3)
  - (= (peso Recurso4) 4)
  - (= (posicion Recurso4) 4)
  recurso5:
  - (enSuelo Recurso5)
  - (requiere Recurso5 Recurso4)
  - (= (peso Recurso5) 2)
  - (= (posicion Recurso5) 5)
  recurso6:
  - (enSuelo Recurso6)
  - (requiere Recurso6 Recurso5)
  - (= (peso Recurso6) 0)
  - (= (posicion Recurso6) 6)
  recurso7:
  - (enSuelo Recurso7)
  - (requiere Recurso7 Recurso6)
  - (= (peso Recurso7) 2)
  - (= (posicion Recurso7) 7)
  avatar:
  - (= (maxPeso) 10)
  - (= (actualPeso) 0)
minizincCorrespondence:
  recurso1:
      existe:
      - recurso1=1;
      no_existe:
      - recurso1=0;
  recurso2:
      existe:
      - recurso2=1;
      no_existe:
      - recurso2=0;
  recurso3:
      existe:
      - recurso3=1;
      no_existe:
      - recurso3=0;
  recurso4:
      existe:
      - recurso4=1;
      no_existe:
      - recurso4=0;
  recurso5:
      existe:
      - recurso5=1;
      no_existe:
      - recurso5=0;
  recurso6:
      existe:
      - recurso6=1;
      no_existe:
      - recurso6=0;
  recurso7:
      existe:
      - recurso7=1;
      no_existe:
      - recurso7=0;
minizinc_to_PDDL_correspondence:
  default: (not (haySalida))
  recurso1=1: (enMochila Recurso1)
  recurso2=1: (enMochila Recurso2)
  recurso3=1: (enMochila Recurso3)
  recurso4=1: (enMochila Recurso4)
  recurso5=1: (enMochila Recurso5)
  recurso6=1: (enMochila Recurso6)
  recurso7=1: (enMochila Recurso7)
  recurso8=1: (enMochila Recurso8)
  recurso9=1: (enMochila Recurso9)
  recurso10=1: (enMochila Recurso10)
  recurso11=1: (enMochila Recurso11)
  recurso12=1: (enMochila Recurso12)
  recurso13=1: (enMochila Recurso13)
  recurso14=1: (enMochila Recurso14)
  recurso15=1: (enMochila Recurso15)
  recurso16=1: (enMochila Recurso16)
  recurso17=1: (enMochila Recurso17)
  recurso18=1: (enMochila Recurso18)
  recurso19=1: (enMochila Recurso19)
  recurso20=1: (enMochila Recurso20)
  recurso21=1: (enMochila Recurso21)
  recurso22=1: (enMochila Recurso22)
  recurso23=1: (enMochila Recurso23)
  recurso24=1: (enMochila Recurso24)
pddl_to_agent_correspondence:
  COGER: take
  RECURSO1: recurso1
  RECURSO2: recurso2
  RECURSO3: recurso3
  RECURSO4: recurso4
  RECURSO5: recurso5
  RECURSO6: recurso6
  RECURSO7: recurso7
  SALIR: closedoor
  SOLTAR: drop
values_correspondence:
  recurso1_peso: 1
  recurso1_score: 1
  recurso2_peso: 2
  recurso2_score: 2
  recurso3_peso: 3
  recurso3_score: 3
  recurso4_peso: 4
  recurso4_score: 4
  recurso5_peso: 2
  recurso5_score: 5
  recurso6_peso: 0
  recurso6_score: 5
  recurso7_peso: 2
  recurso7_score: 4
  maxPeso: 10

